[build]
  command = "npm run build"
  publish = "frontend/build"

[context.production.environment]
  REACT_APP_API_URL = "https://rebus-ceo-dilemma.onrender.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://rebus-ceo-dilemma.onrender.com"
